### PR TITLE
WIP: Master prettier backup

### PR DESCRIPTION
**Pull request by darylthayilporch**

### CODE REVIEW

**Comment by darylthayilporch** [comment]
@jasonnutter WIP, added removal 
Need to add tag before merging (or after i guess)

**Comment by darylthayilporch** [comment]
cc @jasonn-porch @pwmckenna   major version to avoid breaking builds

**Comment by darylthayilporch** [comment]
Ive been convinced to go minor again

**Comment by darylthayilporch** [comment]
will aim to push this later today and fix what comes out of it

**Comment by jasonnutter** [comment]
Strongly disagree. This has proved to break things.

**Comment by jasonnutter** [comment]
What's the argument for making this minor?

**Comment by pwmckenna** [comment]
the argument is that if its major it'll just never happen. at which point, why do it at all. i'm not strongly in favor of doing this at all, but doing a major version without immediately committing to doing all the work to upgrade every repo is my least favorite option.

**Comment by jasonnutter** [comment]
You can still commit to doing the upgrade work without also potentially breaking everyone's build, especially since this impacts all of our frontend repos. By making this a minor, in theory you are just making it so you **have** to fix all the repos immediately, instead being able to take your time.

**Comment by darylthayilporch** [comment]
If we don't think it adds a ton of value and its more of a pain than its worth I am fine scrapping this pr.

**Comment by jasonnutter** [comment]
We can also wait for now and chat about it on Monday, since we didn't a chance to do that this week.

**Comment by darylthayilporch** [comment]
Sounds good will put back WIP on this

**Comment by darylthayilporch** [comment]
closing to make separate module

**Pull request closed without merging**
